server:
  port: 10004

spring:
  application:
    name: gulimall-product
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_pms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      # 以下配置项必须填写
      username: 'nacos'
      password: 'nacos'
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:gulimall-product.yaml?refreshEnabled=true&group=DEFAULT_GROUP

mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.gulimall.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

