server:
  port: 10001

spring:
  application:
    name: gulimall-gateway
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: lb://gulimall-admin
          predicates:
            - Path=/main/**
          filters:
            - RewritePath=/main/(?<segment>.*),/admin/$\{segment}
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/product/**
    nacos:
      serverAddr: 127.0.0.1:8848
      # 以下配置项必须填写
      username: 'nacos'
      password: 'nacos'
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:gulimall-gateway.yaml?refreshEnabled=true&group=DEFAULT_GROUP


